development:
  adapter: postgresql
  database: quest_for_life_development
  host: localhost
  username: postgres
  password: 

test:
  adapter: postgresql
  database: quest_for_life_test
  host: localhost
  username: postgres
  password: 
